// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Web ke liye return karwa rahe hain
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Android configuration (existing)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFUs8ybatemZWg1yIEAopnMVWK1nYkSmM',
    appId: '1:704943362412:android:069dcca13110351894a349',
    messagingSenderId: '704943362412',
    projectId: 'wishmate-9e59f',
    storageBucket: 'wishmate-9e59f.firebasestorage.app',
  );

  // Web configuration (update with your Firebase Console values)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPUW-ivq23nbMgE9OpGeQRhHhB0gsMLhE',
    appId: '1:704943362412:web:e07ffa3e4966d41494a349',
    messagingSenderId: '704943362412',
    projectId: 'wishmate-9e59f',
    storageBucket: 'wishmate-9e59f.appspot.com',
    authDomain: 'wishmate-9e59f.firebaseapp.com',
    measurementId: 'YOUR_MEASUREMENT_ID', // optional
  );
}
